export enum ModalType {
  MOBILITY_PASSENGER_ROAD = 'MOBILITY_PASSENGER_ROAD',

  MOBILITY_PASSENGER_ROAD_CONV = 'MOBILITY_PASSENGER_ROAD_CONV',

  MOBILITY_PASSENGER_ROAD_RE = 'MOBILITY_PASSENGER_ROAD_RE',

  MOBILITY_PASSENGER_RAIL = 'MOBILITY_PASSENGER_RAIL',

  MOBILITY_PASSENGER_RAIL_CONV = 'MOBILITY_PASSENGER_RAIL_CONV',

  MOBILITY_PASSENGER_RAIL_RE = 'MOBILITY_PASSENGER_RAIL_RE',

  MOBILITY_PASSENGER_AIR = 'MOBILITY_PASSENGER_AIR',

  MOBILITY_PASSENGER_AIR_CONV = 'MOBILITY_PASSENGER_AIR_CONV',

  MOBILITY_PASSENGER_AIR_RE = 'MOBILITY_PASSENGER_AIR_RE',

  MOBILITY_FREIGHT_ROAD = 'MOBILITY_FREIGHT_ROAD',

  MOBILITY_FREIGHT_ROAD_CONV = 'MOBILITY_FREIGHT_ROAD_CONV',

  MOBILITY_FREIGHT_ROAD_RE = 'MOBILITY_FREIGHT_ROAD_RE',

  MOBILITY_FREIGHT_RAIL = 'MOBILITY_FREIGHT_RAIL',

  MOBILITY_FREIGHT_RAIL_CONV = 'MOBILITY_FREIGHT_RAIL_CONV',

  MOBILITY_FREIGHT_RAIL_RE = 'MOBILITY_FREIGHT_RAIL_RE',

  MOBILITY_FREIGHT_SHIP = 'MOBILITY_FREIGHT_SHIP',

  MOBILITY_FREIGHT_SHIP_CONV = 'MOBILITY_FREIGHT_SHIP_CONV',

  MOBILITY_FREIGHT_SHIP_RE = 'MOBILITY_FREIGHT_SHIP_RE',
}
