package com.om4a.ct2s.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FactPowerProductionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactPowerProductionAllPropertiesEquals(FactPowerProduction expected, FactPowerProduction actual) {
        assertFactPowerProductionAutoGeneratedPropertiesEquals(expected, actual);
        assertFactPowerProductionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactPowerProductionAllUpdatablePropertiesEquals(FactPowerProduction expected, FactPowerProduction actual) {
        assertFactPowerProductionUpdatableFieldsEquals(expected, actual);
        assertFactPowerProductionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactPowerProductionAutoGeneratedPropertiesEquals(FactPowerProduction expected, FactPowerProduction actual) {
        assertThat(actual)
            .as("Verify FactPowerProduction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactPowerProductionUpdatableFieldsEquals(FactPowerProduction expected, FactPowerProduction actual) {
        assertThat(actual)
            .as("Verify FactPowerProduction relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactPowerProductionUpdatableRelationshipsEquals(FactPowerProduction expected, FactPowerProduction actual) {
        assertThat(actual)
            .as("Verify FactPowerProduction relationships")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getTechnology()).as("check technology").isEqualTo(expected.getTechnology()))
            .satisfies(a -> assertThat(a.getFuel()).as("check fuel").isEqualTo(expected.getFuel()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }
}
