package com.om4a.ct2s.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FuelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelAllPropertiesEquals(Fuel expected, Fuel actual) {
        assertFuelAutoGeneratedPropertiesEquals(expected, actual);
        assertFuelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelAllUpdatablePropertiesEquals(Fuel expected, Fuel actual) {
        assertFuelUpdatableFieldsEquals(expected, actual);
        assertFuelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelAutoGeneratedPropertiesEquals(Fuel expected, Fuel actual) {
        assertThat(actual)
            .as("Verify Fuel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelUpdatableFieldsEquals(Fuel expected, Fuel actual) {
        assertThat(actual)
            .as("Verify Fuel relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelUpdatableRelationshipsEquals(Fuel expected, Fuel actual) {
        // empty method
    }
}
