package com.om4a.ct2s.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class YearAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertYearAllPropertiesEquals(Year expected, Year actual) {
        assertYearAutoGeneratedPropertiesEquals(expected, actual);
        assertYearAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertYearAllUpdatablePropertiesEquals(Year expected, Year actual) {
        assertYearUpdatableFieldsEquals(expected, actual);
        assertYearUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertYearAutoGeneratedPropertiesEquals(Year expected, Year actual) {
        assertThat(actual)
            .as("Verify Year auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertYearUpdatableFieldsEquals(Year expected, Year actual) {
        assertThat(actual)
            .as("Verify Year relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertYearUpdatableRelationshipsEquals(Year expected, Year actual) {
        // empty method
    }
}
